//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.01 at 09:18:13 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "soap-products", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package soap_products;
