INSERT INTO PRICE (id, value, PRODUCT_ID) VALUES (1, 1000, 1);
INSERT INTO PRICE (id, value, PRODUCT_ID) VALUES (2, 2000, 2);
INSERT INTO PRICE (id, value, PRODUCT_ID) VALUES (3, 3000, 3);
INSERT INTO PRICE (id, value, PRODUCT_ID) VALUES (4, 4000, 4);
INSERT INTO PRICE (id, value, PRODUCT_ID) VALUES (5, 5000, 5);